In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 4, 5])

In [3]:
arr

array([1, 2, 4, 5])

In [4]:
index = 2

In [5]:
value = 3

In [6]:
new_arr = np.zeros(len(arr) + 1, dtype=int)

In [7]:
new_arr

array([0, 0, 0, 0, 0])

In [8]:
for i in range(index):
    new_arr[i] = arr[i]

# Insert the new value at the specified index
new_arr[index] = value

In [9]:
new_arr

array([1, 2, 3, 0, 0])

In [10]:
# Copy remaining elements after the inserted value
for i in range(index, len(arr)):
    new_arr[i + 1] = arr[i]

In [11]:
new_arr

array([1, 2, 3, 4, 5])

# Using fuction

In [18]:
ar  = [10,30,40,50]

In [19]:
ar

[10, 30, 40, 50]

In [20]:
ar.insert(1, 20)  # Insert 20 at index 1

In [21]:
ar

[10, 20, 30, 40, 50]

In [22]:
ar.append(60)

In [23]:
ar

[10, 20, 30, 40, 50, 60]

In [24]:
ar.extend([70, 80])

In [26]:
ar

[10, 20, 30, 40, 50, 60, 70, 80]